Fix actor sample + remove HTTP reference in docs and code.
dapr/java-sdk pull request #407
Opened 2020-12-10 03:17 UTC by artursouza

# Description

Fix actor sample + remove HTTP reference in docs and code.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: N/A

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [ ] Created/updated tests
* [X] Extended the documentation

2020-12-10 05:14 UTC, mukundansundar commented on examples/src/main/java/io/dapr/examples/actors/DemoActorService.java
>   * dapr run --components-path ./components --app-id demoactorservice --app-port 3000 --dapr-http-port 3005 \
should the http port be removed here?

2020-12-10 05:39 UTC, artursouza commented on examples/src/main/java/io/dapr/examples/actors/DemoActorService.java
>   * dapr run --components-path ./components --app-id demoactorservice --app-port 3000 --dapr-http-port 3005 \
Yes. Thanks for reminding me.

2020-12-10 08:53 UTC, mukundansundar approved these changes

2020-12-10 08:58 UTC, mukundansundar requested changes
integration tests are failing. 
Additionally there is some small mistake with logging. 
In receiveReminder test
```
Size of timer count list is %d, which means it's been invoked half that many times6
```

```
 System.out.printf(
        "Size of reminder count list is %d, which means it's been invoked half that many times.", calls.size());
```

2020-12-11 21:54 UTC, mukundansundar approved these changes

2020-12-11 21:54 UTC, merged