Modify the pubsub example to have custom span.
dapr/java-sdk pull request #538
Opened 2021-04-30 18:40 UTC by artursouza

# Description

Added tracing example to PubSub.
Included command validation.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #537 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [X] Extended the documentation

2021-04-30 18:45 UTC, mukundansundar approved these changes

2021-04-30 19:01 UTC, mukundansundar requested changes

2021-04-30 19:01 UTC, mukundansundar commented on examples/src/main/java/io/dapr/examples/pubsub/http/README.md
> +dapr run --components-path ./components/pubsub --app-id publisher -- java -jar target/dapr-java-sdk-examples-exec.jar io.dapr.examples.pubsub.http.PublisherWithTracing
please change --app-id ... Same app-id cannot exist with dapr run.

2021-04-30 21:42 UTC, artursouza commented on examples/src/main/java/io/dapr/examples/pubsub/http/README.md
> +dapr run --components-path ./components/pubsub --app-id publisher -- java -jar target/dapr-java-sdk-examples-exec.jar io.dapr.examples.pubsub.http.PublisherWithTracing
Makes sense.

2021-04-30 21:43 UTC, artursouza commented on examples/src/main/java/io/dapr/examples/pubsub/http/PublisherWithTracing.java
> +          String message = String.format("This is message #%d", i);
Makes sense.

2021-04-30 21:57 UTC, halspang reviewed
Seems like the examples are failing to build while they're fine on master. Not sure how this change could've broken them but is that something we should check out?

2021-05-01 17:21 UTC, artursouza commented
I will take a look.

2021-05-03 17:45 UTC, artursouza commented
> I will take a look.

For some reason, it was doing findbug checks on examples. Which did not do after I reran it. Locally, I had the same experience but it worked after I did a mvn clean.

2021-05-03 18:21 UTC, mukundansundar approved these changes

2021-05-03 18:26 UTC, merged