Adding pubsub routing support
dapr/java-sdk pull request #631
Opened 2021-09-15 16:30 UTC by pkedy

# Description

Adding a rule attribute to the topic annotation to utilize PubSub routing.

## Issue reference

dapr/dapr#2582

## Checklist

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

2021-09-17 22:53 UTC, artursouza requested changes
LGTM overall. Just some minor comments.

2021-09-17 22:53 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprSubscriptionBuilder.java
> +  public void setDefaultPath(String path) {
nit: we return the object back in the setters, to offer fluent API.

2021-09-17 22:53 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprSubscriptionBuilder.java
> +  public void addRule(String path, String match, int priority) {
same.

2021-09-17 22:53 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprTopicSubscription.java
> -  public DaprTopicSubscription(String pubsubName, String topic, String route, Map<String, String> metadata) {
This is a breaking change. Please, keep the original constructor and add a new one instead.

2021-09-17 22:53 UTC, artursouza commented on sdk/src/main/java/io/dapr/Rule.java
> +   * Priority of the rule used for ordering.
Explain here if lower number = higher priority.

2021-09-17 22:53 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprSubscriptionBuilder.java
> +public class DaprSubscriptionBuilder {
Does this really need to be public? Make it package visible if possible. It is only used in a private property.

2021-09-17 22:53 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprTopicKey.java
> +public class DaprTopicKey {
Same. Can this be package visible only?

2021-09-17 22:53 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprTopicRule.java
> +public class DaprTopicRule {
Same. Package visible?

2022-01-26 07:46 UTC, johnou commented
ping @pkedy

2022-03-22 04:05 UTC, artursouza commented
This PR is idle and available to anyone that would like to take over and then create a new PR to replace this one.

2022-06-22 19:15 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprSubscriptionBuilder.java
> +  public void setDefaultPath(String path) {
done.

2022-06-22 19:15 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprSubscriptionBuilder.java
> +  public void addRule(String path, String match, int priority) {
done.

2022-06-22 19:17 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprTopicSubscription.java
> -  public DaprTopicSubscription(String pubsubName, String topic, String route, Map<String, String> metadata) {
Done.

2022-06-23 18:39 UTC, artursouza approved these changes

2022-06-23 18:40 UTC, merged