[WIP] Add Jazzer configuration to run in an Action
dapr/java-sdk pull request #664
Opened 2021-12-07 13:47 UTC by sahansera

# Description

Based on the discussion on #510 I thought it might be a good idea to receive some early feedback on some of the questions I had per comment [here](https://github.com/dapr/java-sdk/issues/510#issuecomment-985251690). In summary, what this does is:

- Add a new workflow to trigger the Jazzer testing. Currently, I target the previously built version to keep this as a separate job.
- Invoke `jazzer.sh` which is a Bash script I wrote to run Jazzer against a given set of classes and methods. Currently, the Class and method names are hardcoded under the `jobs.build.runs-on.strategy.matrix.include` for this proof-of-concept. This can be sourced differently (eg: YAML or a code scan)
- In each Jazzer run, a Docker container gets spun up, runs autofuzzing, and dumps the file(s) to a mounted volume on the current Action container.
- These collected files are published to the workflow pipeline. An example can be found [here](https://github.com/sahansera/DaprJazzerTest/actions/runs/1549565377) under the Artifacts section.

Happy to know any feedback on this.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2022-02-01 23:35 UTC, artursouza requested changes

2023-12-21 15:10 UTC, cicoyle commented
gentle ping - @sahansera

2024-02-19 21:47 UTC, cicoyle commented
gentle ping @sahansera

2024-06-19 14:46 UTC, cicoyle commented
gentle ping @sahansera

2025-03-19 18:54 UTC, salaboy commented
closing due inactivity @cicoyle

2025-03-19 18:54 UTC, closed without merging