support invokeXXX return Response
dapr/java-sdk pull request #755
Opened 2022-06-27 06:43 UTC by naah69

# Description

add `DaprResponse` interface and `HttpDaprResponse`,`GrpcDaprRespnse` implement.

## Issue reference

#751 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

2022-06-28 21:59 UTC, tanvigour commented
Please resolve the conflicts

2022-06-29 06:03 UTC, naah69 commented
> Please resolve the conflicts

it had resolved.

2022-07-08 18:03 UTC, artursouza requested changes
We will not support invoke via gRPC anymore. Only HTTP. Please, change this PR to make the invoke method to be over HTTP only - you can use the PreviewClient interface for that.

2022-07-10 09:13 UTC, naah69 commented
> change

ok i will change it .

2022-07-13 06:49 UTC, mukundansundar commented
@skyao Can you review this PR?

2022-07-22 02:51 UTC, naah69 reviewed
it had changed.
@artursouza

2022-07-22 02:53 UTC, naah69 reviewed
it changed

2022-07-22 02:58 UTC, naah69 reviewed
viewed

2022-08-08 14:39 UTC, naah69 commented
any progress?

2022-09-07 08:24 UTC, mukundansundar commented
@naah69 Can you please fix the conflicts in the PR?

2024-02-19 21:45 UTC, cicoyle commented
gentle ping @naah69

2024-09-11 10:16 UTC, imerljak commented
Is this still alive? Would be really nice to have it in order to get proper response status.

2025-01-31 21:48 UTC, cicoyle commented
gentle ping @naah69 - mind resolving the conflicts?

2025-03-19 18:57 UTC, closed without merging

2025-03-19 18:57 UTC, salaboy commented
I am closing this PR due inactivity. @imerljak do you still need this functionality. Can you please elaborate which APIs are you using that are not returning what you expect? Can you please create an issue so we can discuss that?