Update sdk to use configuration dictionaries
dapr/java-sdk pull request #769
Opened 2022-08-27 21:15 UTC by addjuarez

Signed-off-by: addjuarez <addiajuarez@gmail.com>

# Description

Updated sdk to use configuration dictionaries instead of lists

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #746 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

2022-08-30 11:22 UTC, pravinpushkar commented on sdk/src/main/java/io/dapr/client/DaprPreviewClient.java
>     * @return Mono of List of ConfigurationItems
Here also and probably all other places this change affects.

2022-08-30 18:37 UTC, artursouza requested changes

2022-08-30 18:37 UTC, artursouza commented on sdk/src/main/java/io/dapr/client/DaprClientGrpc.java
> +          return configMap;
Return an immutable map, please.

2022-09-01 20:24 UTC, tanvigour approved these changes

2022-09-05 05:49 UTC, pravinpushkar approved these changes
lgtm. @mukundansundar @artursouza Code cov check is failing for now but I can take care in my subsequent PR mentioned above.

2022-09-06 02:28 UTC, artursouza approved these changes

2022-09-06 02:28 UTC, merged