[Docs] Add input bindings section
dapr/java-sdk pull request #776
Opened 2022-09-09 18:18 UTC by hhunter-ms

Signed-off-by: Hannah Hunter <hannahhunter@microsoft.com>

# Description

Add input bindings section to Java doc.

## Issue reference

PR will close: dapr/docs#2770

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2022-09-13 01:27 UTC, artursouza requested changes

2022-09-13 01:27 UTC, artursouza commented on daprdocs/content/en/java-sdk-docs/_index.md
> +        @PostMapping(path = "/checkout")
Please, include the method too since annotations don't work by themselves.

2022-09-13 20:41 UTC, hhunter-ms commented
@artursouza updated - let me know if this example fits with the other Java SDK examples, too

2022-09-14 18:23 UTC, artursouza approved these changes

2022-09-14 18:23 UTC, merged