Add Actor Timer/Reminder option builders
dapr/java-sdk pull request #808
Opened 2022-11-14 23:51 UTC by addjuarez

Signed-off-by: addjuarez <addiajuarez@gmail.com>

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

2022-11-18 20:22 UTC, tanvigour approved these changes

2022-11-18 20:27 UTC, mukundansundar commented on sdk-actors/src/main/java/io/dapr/actors/runtime/ReminderOptions.java
> +  public static class ReminderOptionsBuilder<T> {
I think we specifically moved away from boiler pattern in java sdk for model classes https://github.com/dapr/java-sdk/issues/587. 
Can this be changed to reflect that?

2022-11-18 20:27 UTC, mukundansundar commented on sdk-actors/src/main/java/io/dapr/actors/runtime/TimerOptions.java
> +  private TimerOptions(TimerOptionsBuilder builder) {
same here .

2022-11-18 20:28 UTC, mukundansundar requested changes
please remove builder pattern for model classes see https://github.com/dapr/java-sdk/issues/587

2022-11-18 20:32 UTC, mukundansundar commented on sdk-actors/src/main/java/io/dapr/actors/runtime/TimerOptions.java
> +  public static class TimerOptionsBuilder<T> {
same here

2023-01-05 00:29 UTC, addjuarez commented
Can you clarify what changes are needed? I removed the builder and tried using https://azure.github.io/azure-sdk/java_introduction.html#java-models-builder

2023-05-24 21:26 UTC, artursouza requested changes
We need unit tests and support for ISO duration.

2023-10-30 15:52 UTC, closed without merging