Enable dead letter topic
dapr/java-sdk pull request #848
Opened 2023-04-24 07:57 UTC by charlieMk1

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #777 Add support for DLQ (dead letter queue)

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X ] Code compiles correctly
* [X] Created/updated tests
* [X] Extended the documentation

2023-04-24 17:25 UTC, artursouza requested changes
Some minor comments. It is at the right direction. Thanks for your contribution.

2023-04-24 17:25 UTC, artursouza commented on sdk-springboot/src/test/java/io/dapr/springboot/DaprRuntimeTest.java
> +            pubSubName, topicName, match, rule.priority(), firstRoute,deadLetterTopic, metadata);
nit: space after ","

2023-04-24 17:25 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprTopicSubscription.java
> +  DaprTopicSubscription(String pubsubName, String topic, String route, String deadLetterTopic,
Please, keep these small for simpler scenarios. For complete params, just add to the last one. Optionally, create new variations by adding deadletterTopic, but don't change existing ones.

2023-04-24 17:25 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprTopicSubscription.java
> +  DaprTopicSubscription(String pubsubName, String topic, String route, String deadLetterTopic,
This is the one that contains all params, so this is correct. The others should remain untouched or have new ones added with deadLetterTopic. It is unfortunate that Java requires all permutations of params to be declared as each separate function overload.

2023-04-24 17:25 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprRuntime.java
> +      String deadLetterTopic,
This is a breaking change. You would need to undo this and create a new method overload instead.

2023-04-24 17:25 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprRuntime.java
> +      String deadLetterTopic,
Please, create a new method overload with the previous signature to avoid this from being a breaking change.

2023-04-24 17:25 UTC, artursouza commented on sdk-springboot/src/main/java/io/dapr/springboot/DaprBeanPostProcessor.java
> +                pubSubName, topicName, match, rule.priority(), route,deadLetterTopic, metadata, bulkSubscribe);
nit: space after ,

2023-05-24 19:36 UTC, artursouza requested changes

2023-05-24 19:36 UTC, artursouza commented on examples/src/main/java/io/dapr/examples/pubsub/http/SubscriberController.java
> +  @PostMapping(path = "/testingtopic")
This is breaking integration tests, please, use a different topic name and post mapping.

2023-09-14 18:20 UTC, cicoyle commented
I opened [the above PR](https://github.com/dapr/java-sdk/pull/913) to get this PR to a mergeable state, since I don't have permission to push to Charlie's branch

2023-09-15 00:28 UTC, closed without merging