[docs][WIP] Workflow docs
dapr/java-sdk pull request #890
Opened 2023-08-02 20:11 UTC by hhunter-ms

# Description

Add docs alongside new Java SDK workflow example

## Issue reference

PR will close: #881 
Related issue and PR:
  - #857 
  - #839 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2023-08-02 20:18 UTC, hhunter-ms commented
/assign

2023-09-13 16:18 UTC, hhunter-ms commented
@bderusha @macromania I did some rearranging of _index.md pages, but do you mind taking a look at the documentation for the workflow Java SDK sample (java-workflow.md) and the workflow client sample (java-client.md)?

2023-09-13 22:25 UTC, msfussell approved these changes
LGTM

2023-09-13 23:07 UTC, RyanLettieri requested changes
One small comment

2023-09-13 23:07 UTC, RyanLettieri commented on daprdocs/content/en/java-sdk-docs/_index.md
> +Put the Dapr Java SDK to the test. Walk through the Java quickstarts adn tutorials to see Dapr in action:
change "adn" to "and"

2023-09-20 22:38 UTC, artursouza approved these changes

2023-09-20 23:16 UTC, merged