fix flaky integration test SdkResiliencytIT
dapr/java-sdk pull request #960
Opened 2023-11-21 14:00 UTC by MregXN

# Description
It currently fail due to `toxiClientErrorCount` is not greater than `retryOneClientErrorCount`. **But it's theoretically possible**. I increase `NUM_ITERATIONS` to further reduce this probability.

What is more, it is also possible that none of the attempts succeed. It should try again at this moment instead of directly determining the test failed.
## Issue reference

Please refer to the the point 4 of issue [#7128](https://github.com/dapr/dapr/issues/7128) in dapr/dapr.

2023-11-21 16:24 UTC, mukundansundar requested changes

2023-11-21 16:24 UTC, mukundansundar commented on sdk-tests/src/test/java/io/dapr/it/resiliency/SdkResiliencytIT.java
> +      }
```suggestion
      if(toxiClientErrorCount.get() < NUM_ITERATIONS && retryOneClientErrorCount.get() < NUM_ITERATIONS){
        // This assertion makes sure that toxicity is on
        assertTrue(toxiClientErrorCount.get() > 0);
        assertTrue(retryOneClientErrorCount.get() > 0);
        // A client without retries should have more errors than a client with one retry.
        assertTrue(toxiClientErrorCount.get() > retryOneClientErrorCount.get());
        break;
      }
      toxiClientErrorCount.set(0);
      retryOneClientErrorCount.set(0);
```

2023-11-21 16:24 UTC, mukundansundar commented on sdk-tests/src/test/java/io/dapr/it/resiliency/SdkResiliencytIT.java
> +    while (shouldRetry){
```suggestion
    while (true){
```

2023-11-21 16:24 UTC, mukundansundar commented on sdk-tests/src/test/java/io/dapr/it/resiliency/SdkResiliencytIT.java
> +    boolean shouldRetry = true;
```suggestion
```

2023-11-22 07:28 UTC, MregXN commented
@mukundansundar ready to review

2023-11-27 22:06 UTC, artursouza approved these changes

2023-12-04 19:01 UTC, mukundansundar approved these changes

2023-12-11 05:08 UTC, merged