Improving and Adding Logs for Workflow
dapr/java-sdk pull request #978
Opened 2023-12-26 19:10 UTC by RyanLettieri

# Description

Added in logging statements for dapr workflow and optional parameter for setting the log level

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #946 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2024-01-03 15:12 UTC, mukundansundar commented
@RyanLettieri Can you look into the coverage checks that are failing in this PR?

2024-01-03 15:15 UTC, RyanLettieri commented
> @RyanLettieri Can you look into the coverage checks that are failing in this PR?

The coverage checks are due to the switch case statement for the log levels. We log what the log level was set to in the switch case statements, I.e. "Severe", "Warning", etc. I didn't believe it made much sense to create test cases for each individual log level but if needed I certainly can.

2024-01-04 00:30 UTC, artursouza requested changes

2024-01-04 00:30 UTC, artursouza commented on sdk-workflows/src/main/java/io/dapr/workflows/runtime/WorkflowRuntimeBuilder.java
> +  private void setLogLevel() {
In Java, log level and date format is done from the application's perspective. See the example here: https://github.com/dapr/java-sdk/blob/master/examples/src/main/resources/logback.xml

If you need this from the test's perspective, you can modify this class to have a private constructor that will receive the custom logger from the test.

2024-01-05 22:55 UTC, artursouza approved these changes

2024-01-06 00:21 UTC, merged